### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by jan569** [mmsbld/LLMR#2]
### NO-CODE: Tests & GitHub Issues
- [ ] Tests durchführen und GitHub-Issues prüfen

### CODING: C#.NET
- [ ] Fix: "Object reference not set" Fehler in python.net 3.04 (Singleton war nicht notwendig, Instanziierung nur einmal erlaubt)
- [ ] Console automatisch hochklappen bei Python-Installation (und nach `IsBusy=True` wieder einklappen, falls vorher collapsed)
- [ ] Update: Sicherheitswarnung für "System.Text.Json" 8.0.4 beachten (Details: [GHSA-8g4q-xg66-9fp4](https://github.com/advisories/GHSA-8g4q-xg66-9fp4))
- [ ] Verbessern: UNBEARABLE ViewModel optimieren

### CODING: Python
- [ ] Aufräumen und Refactoring: unbenutzte oder überflüssige Code-Teile entfernen
- [ ] "Console Copy Last" Funktion überprüfen (möglicherweise unnötig)
- [ ] Video mit Jan zur Funktionalität und Code-Besprechung aufnehmen

### UI / UX Verbesserungen
- **Data Collection Tab:**
  - [ ] Kontextmenü aktivieren, so dass "Umbenennen" möglich ist
  - [ ] Drag & Drop-Funktionalität (auch auf mobilen Geräten)
  - [ ] Alte Platzhalter-Dateien hinzufügen (z. B. 31.12.1969)

- **PDF-Export Funktionalität:**
  - [ ] Schritt 1: Alle Settings / Parameter / Key / Date etc. in PDF exportieren
  - [ ] Einheitliches, erweiterbares Format für PDFs (kompatibel mit alten Dateien)
  - [ ] (JSON) -> PDF (und zurück!); XML-Unterstützung prüfen

### Allgemeine Aufgaben
- [ ] Konsolidierung und Aufräumen: C#.NET-Code (Cleanup, Refactoring & Unit-Tests)
- [ ] Konsolidierung und Aufräumen: AXAML-Markup und HTML-ähnliche Struktur
- [ ] Python-Aufgaben: Rücksprache mit Tobi für spezifische Fragen und Optimierungen
