### ISSUE TITLE
ToDo: (vor public)

### ISSUE THREAD

**Issue by mmsbld** [mmsbld/LLMR#3]
## PRE- "Veröffentlichung" (also github auf public)

# General
- [ ] #8
- [ ] #9

# GitHub "managen" --> JAN :heart: 
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7
- [ ] #10
- [ ] release versions distribution (Wie können die verschiedenen Versionen released werden? Also pro Versionsnummer mindestens: Mac arm64 & Win x64, außerdem: Ordner mit Dokumenten in denen nuget & python packages gelistet sind bzw. jeweils dazu zum "release bundle", in dem dann die release versionen stecken & einmal eben package nummern

# Weiterentwicklung / Zukunftsvision :rocket: 
- [ ] Automatisierte Datenauswertung: ML
- [ ] Streamlined approach: quant. content ana.
- [ ] potential: large scale chat history analysis (--> one day, even automated); why not?
